import {Auth0ContextInterface, User} from "@auth0/auth0-react";
import {API} from "common/src/api/endpoints.ts";

import {addTokenHeader} from "@/lib/auth.ts";

/**
 * Returns the ID of the currently logged in user if they're an employee using a token generated by {@link getAccessTokenSilently}.
 */
export const getIdFromUser = async (
    token: Awaited<ReturnType<Auth0ContextInterface<User>["getAccessTokenSilently"]>>
) => {
    return await fetch(API.USERS.ROUTE, await addTokenHeader(token))
        .then((res) => res.json())
        .then((json) => API.USERS.RES.parse(json).id);
};

/**
 * Returns the position of the currently logged in user if they're an employee using a token generated by {@link getAccessTokenSilently}.
 */
export const getPositionFromUser = async (
    token: Awaited<ReturnType<Auth0ContextInterface<User>["getAccessTokenSilently"]>>
) => {
    return await fetch(API.USERS.ROUTE, await addTokenHeader(token))
        .then((res) => res.json())
        .then((json) => API.USERS.RES.parse(json).position);
};

/**
 * Returns the ID and position of the currently logged in user if they're an employee using a token generated by {@link getAccessTokenSilently}.
 */
export const getDataFromUser = async (
    token: Awaited<ReturnType<Auth0ContextInterface<User>["getAccessTokenSilently"]>>
) => {
    return await fetch(API.USERS.ROUTE, await addTokenHeader(token))
        .then((res) => res.json())
        .then((json) => API.USERS.RES.parse(json));
};
