enableGlobalCache: false
globalFolder: ".yarn/global"
packageExtensions:
    "tunnel-rat@*":
        dependencies:
            react: "*"
    "use-sync-external-store@*":
        peerDependencies:
            react: "*"
    "react@*":
        dependencies:
            "react/jsx-runtime": "*"
            "react/jsx-dev-runtime": "*"
