export type EmployeeSeed = {
    uuid: string;
    userName: string;
    firstName: string;
    lastName: string;
    email: string;
    phoneNumber: string;
    password: string;
    position: string;
    department: string;
};

const employeeSeedData = [
    {
        uuid: "auth0|6802e8488773a9cc0ae23daa",
        userName: "admin",
        firstName: "Wilson",
        lastName: "Wong",
        email: "admind25n@gmail.com",
        phoneNumber: "508-446-6912",
        password: "admin",
        position: "admin",
        department: "Emergency Department",
    },
    {
        uuid: "auth0|6811c97687b33ccc37384f8a",
        userName: "staffD25n@gmail.com",
        firstName: "Jose",
        lastName: "Ricardo",
        email: "staffD25n@gmail.com",
        phoneNumber: "206-714-8321",
        password: "IDK",
        position: "employee",
        department: "Urology",
    },
    {
        uuid: "auth0|68165c86821b56fdc024b3bb",
        userName: "softengd25n@gmail.com",
        firstName: "Andy",
        lastName: "Truong",
        email: "softengd25n@gmail.com",
        phoneNumber: "212-121-2121",
        password: "JimboSlice@1282",
        position: "admin",
        department: "Gastroenterology",
    },
    {
        uuid: "auth0|68194f670068995fd182df45",
        userName: "joshbearfield@massgeneralbrigham.co",
        firstName: "Josh",
        lastName: "Bearfield",
        email: "joshbearfield@massgeneralbrigham.co",
        phoneNumber: "415-673-2841",
        password: "JimboSlice@1282",
        position: "employee",
        department: "Radiology",
    },
    {
        uuid: "auth0|681952d1b07a5e3343481811",
        userName: "colebennett@massgeneralbrigham.co",
        firstName: "Cole",
        lastName: "Bennett",
        email: "colebennett@massgeneralbrigham.co",
        phoneNumber: "312-788-5902",
        password: "JimboSlice@1282",
        position: "employee",
        department: "Cardiac Rehab",
    },
    {
        uuid: "auth0|681951f7b07a5e33434817ff",
        userName: "nickcalcasola@massgeneralbrigham.co",
        firstName: "Nick",
        lastName: "Calcasola",
        email: "nickcalcasola@massgeneralbrigham.co",
        phoneNumber: "646-204-9736",
        password: "JimboSlice@1282",
        position: "employee",
        department: "Pharmacy",
    },
    {
        uuid: "auth0|68194db8b07a5e33434817ca",
        userName: "zherenli@massgeneralbrigham.co",
        firstName: "Zheren",
        lastName: "Li",
        email: "zherenli@massgeneralbrigham.co",
        phoneNumber: "702-551-3084",
        password: "JimboSlice@1282",
        position: "employee",
        department: "Neurology",
    },
    {
        uuid: "auth0|6819512eb07a5e33434817f2",
        userName: "mprimavera@showersharts.co",
        firstName: "Micheal",
        lastName: "Primavera",
        email: "mprimavera@showersharts.co",
        phoneNumber: "213-558-9310",
        password: "JimboSlice@1282",
        position: "employee",
        department: "Physical Therapy",
    },
    {
        uuid: "auth0|681955730068995fd182dfae",
        userName: "thomasricci@massgeneralbrigham.co",
        firstName: "Thomas",
        lastName: "Ricci",
        email: "tomricci@massgeneralbrigham.co",
        phoneNumber: "617-720-4412",
        password: "JimboSlice@1282",
        position: "employee",
        department: "Occupational Therapy",
    },
    {
        uuid: "auth0|6819518bb07a5e33434817f7",
        userName: "juttecht@massgeneralbrigham.co",
        firstName: "Jackson",
        lastName: "Uttecht",
        email: "juttecht@massgeneralbrigham.co",
        phoneNumber: "801-638-9507",
        password: "JimboSlice@1282",
        position: "employee",
        department: "Endocrinology",
    },
    {
        uuid: "auth0|681953d40068995fd182df97",
        userName: "danielzhuzhang@massgeneralbrigham.co",
        firstName: "Daniel",
        lastName: "Zhang",
        email: "danielzhuzhang@massgeneralbrigham.co",
        phoneNumber: "919-358-7260",
        password: "JimboSlice@1282",
        position: "employee",
        department: "Obstetrics and Gynecology",
    },
    {
        uuid: "auth0|68194b290068995fd182df06",
        userName: "ivanzheng@massgeneralbrigham.co",
        firstName: "Ivan",
        lastName: "Zheng",
        email: "ivanzheng@massgeneralbrigham.co",
        phoneNumber: "129-313-4141",
        password: "JimboSlice@1282",
        position: "employee",
        department: "Orthopedics",
    },
    {
        uuid: "auth0|681950c50068995fd182df5d",
        userName: "beruhzelleke@massgeneralbrigham.co",
        firstName: "Beruh",
        lastName: "Zelleke",
        email: "beruhzelleke@massgeneralbrigham.co",
        phoneNumber: "818-441-2334",
        password: "JimboSlice@1282",
        position: "employee",
        department: "Pulmonary Services",
    },
];

export default employeeSeedData;
